# Import Libraries

In [ ]:
import pandas as pd
import numpy as np
import os
import matplotlib.pyplot as plt
import seaborn as sns
import scipy

# Importing Data

In [10]:
# Import most recent updated merged data set
ords_prods_custs_merged = pd.read_pickle('/content/drive/MyDrive/Instacart Basket Analysis/02 Data/Prepared Data/Orders_Products_Customers_Merged_Final.pkl')

In [11]:
# Checking shape
ords_prods_custs_merged.shape

(32404859, 30)

In [12]:
ords_prods_custs_merged.dtypes

Unnamed: 0                  int64
Unnamed: 0_x                int64
product_id                  int64
product_name               object
aisle_id                    int64
department_id               int64
prices                    float64
Unnamed: 0_y                int64
order_id                    int64
user_id                    object
eval_set                   object
order_number                int64
order_day_of_week           int64
order_hour_of_day           int64
days_since_prior_order    float64
first_order                  bool
add_to_cart_order           int64
reordered                   int64
_merge                     object
first_name                 object
last_name                  object
gender                     object
state                      object
age                         int64
date_joined                object
number_of_dependants        int64
fam_status                 object
income                      int64
max_order                   int64
loyalty_flag               object
dtype: object




# 03. Handling PII Data

In [13]:
# 'first_name' and 'last_name' columns contain sensitive information since it can be traced back to particular people.
# These columns will not be used in the analysis and a copy of the original dataframe will be created excluding these 2 columns.

In [14]:
# Copy of 'ords_prods_custs_merged' without 'first_name' and 'last_name' columns
ords_prods_custs_merged_2 = ords_prods_custs_merged.drop(columns = ['first_name', 'last_name'])

In [15]:
ords_prods_custs_merged_2.head()

,Unnamed: 0,Unnamed: 0_x,product_id,product_name,aisle_id,department_id,prices,Unnamed: 0_y,order_id,user_id,...,_merge,gender,state,age,date_joined,number_of_dependants,fam_status,income,max_order,loyalty_flag
0,0,0,1,Chocolate Sandwich Cookies,61,19,5.8,1987,3139998,138,...,both,Male,Minnesota,81,8/1/2019,1,married,49620,32,Regular Customer
1,1,0,1,Chocolate Sandwich Cookies,61,19,5.8,1989,1977647,138,...,both,Male,Minnesota,81,8/1/2019,1,married,49620,32,Regular Customer
2,467222,907,907,Premium Sliced Bacon,106,12,20.0,1960,3160996,138,...,both,Male,Minnesota,81,8/1/2019,1,married,49620,32,Regular Customer
3,467223,907,907,Premium Sliced Bacon,106,12,20.0,1969,2254091,138,...,both,Male,Minnesota,81,8/1/2019,1,married,49620,32,Regular Customer
4,490702,1000,1000,Apricots,18,10,12.9,1968,505689,138,...,both,Male,Minnesota,81,8/1/2019,1,married,49620,32,Regular Customer

In [16]:
# The Instacart officers are interested in comparing customer behavior in different geographic areas.
# Create a regional segmentation of the data.
# You’ll need to create a “Region” column based on the “State” column from your customers data set.

# Creating Regional Column

In [17]:
ords_prods_custs_merged_2['state'].value_counts(dropna = False)

Pennsylvania            667082
California              659783
Rhode Island            656913
Georgia                 656389
New Mexico              654494
Arizona                 653964
North Carolina          651900
Oklahoma                651739
Alaska                  648495
Minnesota               647825
Massachusetts           646358
Wyoming                 644255
Virginia                641421
Missouri                640732
Texas                   640394
Colorado                639280
Maine                   638583
North Dakota            638491
Alabama                 638003
Kansas                  637538
Louisiana               637482
Delaware                637024
South Carolina          636754
Oregon                  636425
Arkansas                636144
Nevada                  636139
New York                635983
Montana                 635265
South Dakota            633772
Illinois                633024
Hawaii                  632901
Washington              632852
Mississippi             632675
Kentucky                632490
Michigan                630928
Florida                 629027
Ohio                    628319
Wisconsin               628108
New Jersey              627692
Indiana                 627282
Maryland                626579
Nebraska                625813
Iowa                    625493
Connecticut             623022
Tennessee               617873
New Hampshire           615378
District of Columbia    613695
West Virginia           612296
Utah                    611941
Vermont                 611725
Idaho                   607119
Name: state, dtype: int64

In [18]:
# Creating a list of region values using if-statement with for-loops

region = []

for value in ords_prods_custs_merged_2['state']:
  if (value in ['Maine', 'New Hampshire', 'Vermont', 'Massachusetts', 'Rhode Island', 'Connecticut', 'New York', 'Pennsylvania', 'New Jersey']):
    region.append('Northeast')
  elif (value in ['Wisconsin', 'Michigan', 'Illinois', 'Ohio', 'North Dakota', 'South Dakota', 'Nebraska', 'Minnesota', 'Iowa', 'Missouri']):
    region.append('Midwest')
  elif (value in ['Delaware', 'Maryland', 'District of Columbia', 'Virginia', 'West Virginia', 'North Carolina', 'South Carolina', 'Georgia', 'Florida', 'Kentucky', 'Tennessee', 'Mississippi', 'Alabama', 'Oklahoma', 'Texas', 'Arkansas', 'Louisiana']):
    region.append('South')
  else:
    region.append('West')

In [19]:
# Printing region values
region

['Midwest',
 'Midwest',
 'Midwest',
 'Midwest',
 'Midwest',
 'Midwest',
 'Midwest',
 'Midwest',
 'Midwest',
 'Midwest',
 'Midwest',
 'Midwest',
 'Midwest',
 'Midwest',
 'Midwest',
 'Midwest',
 'Midwest',
 'Midwest',
 'Midwest',
 'Midwest',
 'Midwest',
 'Midwest',
 'Midwest',
 'Midwest',
 'Midwest',
 'Midwest',
 'Midwest',
 'Midwest',
 'Midwest',
 'Midwest',
 'Midwest',
 'Midwest',
 'Midwest',
 'Midwest',
 'Midwest',
 'Midwest',
 'Midwest',
 'Midwest',
 'Midwest',
 'Midwest',
 'Midwest',
 'Midwest',
 'Midwest',
 'Midwest',
 'Midwest',
 'Midwest',
 'Midwest',
 'Midwest',
 'Midwest',
 'Midwest',
 'Midwest',
 'Midwest',
 'Midwest',
 'Midwest',
 'Midwest',
 'Midwest',
 'Midwest',
 'Midwest',
 'Midwest',
 'Midwest',
 'Midwest',
 'Midwest',
 'Midwest',
 'Midwest',
 'Midwest',
 'Midwest',
 'Midwest',
 'Midwest',
 'Midwest',
 'Midwest',
 'Midwest',
 'Midwest',
 'Midwest',
 'Midwest',
 'Midwest',
 'Midwest',
 'Midwest',
 'Midwest',
 'Midwest',
 'Midwest',
 'Midwest',
 'Midwest',
 'Midwest',
 'Midwest',
 'Midwest',
 'Midwest',
 'Midwest',
 'Midwest',
 'Midwest',
 'Midwest',
 'Midwest',
 'Midwest',
 'Midwest',
 'Midwest',
 'Midwest',
 'Midwest',
 'Midwest',
 'Midwest',
 'Midwest',
 'Midwest',
 'Midwest',
 'Midwest',
 'Midwest',
 'Midwest',
 'Midwest',
 'Midwest',
 'Midwest',
 'Midwest',
 'Midwest',
 'Midwest',
 'Midwest',
 'Midwest',
 'Midwest',
 'Midwest',
 'Midwest',
 'Midwest',
 'Midwest',
 'Midwest',
 'Midwest',
 'Midwest',
 'Midwest',
 'Midwest',
 'Midwest',
 'Midwest',
 'Midwest',
 'Midwest',
 'Midwest',
 'Midwest',
 'Midwest',
 'Midwest',
 'Midwest',
 'Midwest',
 'Midwest',
 'Midwest',
 'Midwest',
 'Midwest',
 'Midwest',
 'Midwest',
 'Midwest',
 'Midwest',
 'Midwest',
 'Midwest',
 'Midwest',
 'Midwest',
 'Midwest',
 'Midwest',
 'Midwest',
 'Midwest',
 'Northeast',
 'Northeast',
 'Northeast',
 'Northeast',
 'Northeast',
 'Northeast',
 'Northeast',
 'Northeast',
 'Northeast',
 'Northeast',
 'Northeast',
 'Northeast',
 'Northeast',
 'Northeast',
 'Northeast',
 'Northeast',
 'Northeast',
 'Northeast',
 'Northeast',
 'Northeast',
 'Northeast',
 'Northeast',
 'Northeast',
 'Northeast',
 'Northeast',
 'Northeast',
 'Northeast',
 'Northeast',
 'Northeast',
 'Northeast',
 'Northeast',
 'Northeast',
 'Northeast',
 'Northeast',
 'Northeast',
 'Northeast',
 'Northeast',
 'Northeast',
 'Northeast',
 'Northeast',
 'Northeast',
 'Northeast',
 'Northeast',
 'Northeast',
 'Northeast',
 'Northeast',
 'Northeast',
 'Northeast',
 'Northeast',
 'Northeast',
 'Northeast',
 'Northeast',
 'Northeast',
 'Northeast',
 'Northeast',
 'Northeast',
 'Northeast',
 'Northeast',
 'Northeast',
 'Northeast',
 'Northeast',
 'Northeast',
 'Northeast',
 'Northeast',
 'Northeast',
 'Northeast',
 'Northeast',
 'Northeast',
 'Northeast',
 'Northeast',
 'Northeast',
 'Northeast',
 'Northeast',
 'Northeast',
 'Northeast',
 'Northeast',
 'Northeast',
 'Northeast',
 'Northeast',
 'Northeast',
 'Northeast',
 'Northeast',
 'Northeast',
 'Northeast',
 'Northeast',
 'Northeast',
 'Northeast',
 'Northeast',
 'Northeast',
 'Northeast',
 'Northeast',
 'Northeast',
 'Northeast',
 'Northeast',
 'Northeast',
 'Northeast',
 'Northeast',
 'Northeast',
 'Northeast',
 'Northeast',
 'Northeast',
 'Northeast',
 'Northeast',
 'Northeast',
 'Northeast',
 'Northeast',
 'Northeast',
 'Northeast',
 'Northeast',
 'Northeast',
 'Northeast',
 'Northeast',
 'Northeast',
 'Northeast',
 'Northeast',
 'Northeast',
 'Northeast',
 'Northeast',
 'Northeast',
 'Northeast',
 'Northeast',
 'Northeast',
 'Northeast',
 'Northeast',
 'Northeast',
 'Northeast',
 'Northeast',
 'Northeast',
 'Northeast',
 'Northeast',
 'Northeast',
 'Northeast',
 'Northeast',
 'Northeast',
 'Northeast',
 'Northeast',
 'Northeast',
 'Northeast',
 'Northeast',
 'Northeast',
 'Northeast',
 'Northeast',
 'Northeast',
 'Northeast',
 'Northeast',
 'Northeast',
 'Northeast',
 'Northeast',
 'Northeast',
 'Northeast',
 'Northeast',
 'Northeast',
 'Northeast',
 'Northeast',
 'Northeast',
 'Northeast',
 'Northeast',
 'Northeast',
 'Northeast',
 'Northeast',
 'Northeast',
 'Northeast',
 'Northeast',
 'Northeast',
 'Northeast',
 'Northeast',
 'Northeast',
 'Northeast',
 'Northeast',
 'Northeast',
 'Northeast',
 'Northeast',
 'Northeast',
 'Northeast',
 'Northeast',
 'Northeast',
 'Northeast',
 'Northeast',
 'Northeast',
 'Northeast',
 'Northeast',
 'Northeast',
 'Northeast',
 'Northeast',
 'Northeast',
 'Northeast',
 'Northeast',
 'Northeast',
 'Northeast',
 'Northeast',
 'Northeast',
 'Northeast',
 'Midwest',
 'Midwest',
 'Midwest',
 'Midwest',
 'Midwest',
 'Midwest',
 'Midwest',
 'Midwest',
 'Midwest',
 'Midwest',
 'Midwest',
 'Midwest',
 'Midwest',
 'Midwest',
 'Midwest',
 'Midwest',
 'Midwest',
 'Midwest',
 'Midwest',
 'Midwest',
 'Midwest',
 'Midwest',
 'Midwest',
 'Midwest',
 'Midwest',
 'Midwest',
 'Midwest',
 'Midwest',
 'Midwest',
 'Midwest',
 'Midwest',
 'Midwest',
 'Midwest',
 'Midwest',
 'Midwest',
 'Midwest',
 'Midwest',
 'Midwest',
 'Midwest',
 'Midwest',
 'Midwest',
 'Midwest',
 'Midwest',
 'Midwest',
 'Midwest',
 'Midwest',
 'Midwest',
 'Midwest',
 'Midwest',
 'Midwest',
 'Midwest',
 'Midwest',
 'Midwest',
 'Midwest',
 'Midwest',
 'Midwest',
 'Midwest',
 'Midwest',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 ...]

In [20]:
# Creating new 'region' column within df, using 'region' values
ords_prods_custs_merged_2['region'] = region

In [21]:
# Checking 'region' value counts
ords_prods_custs_merged_2['region'].value_counts(dropna = False)

South        10791885
West          9557733
Midwest       6332505
Northeast     5722736
Name: region, dtype: int64

In [22]:
ords_prods_custs_merged_2.shape

(32404859, 29)

In [23]:
# Checking headers
pd.set_option('display.max_columns', None)
ords_prods_custs_merged_2.head(1)

,Unnamed: 0,Unnamed: 0_x,product_id,product_name,aisle_id,department_id,prices,Unnamed: 0_y,order_id,user_id,eval_set,order_number,order_day_of_week,order_hour_of_day,days_since_prior_order,first_order,add_to_cart_order,reordered,_merge,gender,state,age,date_joined,number_of_dependants,fam_status,income,max_order,loyalty_flag,region
0,0,0,1,Chocolate Sandwich Cookies,61,19,5.8,1987,3139998,138,prior,28,6,11,3.0,False,5,0,both,Male,Minnesota,81,8/1/2019,1,married,49620,32,Regular Customer,Midwest

In [24]:
# The Instacart officers are interested in comparing customer behavior in different geographic areas.
# Create a regional segmentation of the data. You’ll need to create a “Region” column based on the “State” column from your customers data set: 
# a. Use the region information in this Wikipedia article to create your column (you only need to create regions, not divisions)





# Creating Region Column

In [25]:
# Checking value counts of 'state' column
ords_prods_custs_merged_2['state'].value_counts(dropna = False)

Pennsylvania            667082
California              659783
Rhode Island            656913
Georgia                 656389
New Mexico              654494
Arizona                 653964
North Carolina          651900
Oklahoma                651739
Alaska                  648495
Minnesota               647825
Massachusetts           646358
Wyoming                 644255
Virginia                641421
Missouri                640732
Texas                   640394
Colorado                639280
Maine                   638583
North Dakota            638491
Alabama                 638003
Kansas                  637538
Louisiana               637482
Delaware                637024
South Carolina          636754
Oregon                  636425
Arkansas                636144
Nevada                  636139
New York                635983
Montana                 635265
South Dakota            633772
Illinois                633024
Hawaii                  632901
Washington              632852
Mississippi             632675
Kentucky                632490
Michigan                630928
Florida                 629027
Ohio                    628319
Wisconsin               628108
New Jersey              627692
Indiana                 627282
Maryland                626579
Nebraska                625813
Iowa                    625493
Connecticut             623022
Tennessee               617873
New Hampshire           615378
District of Columbia    613695
West Virginia           612296
Utah                    611941
Vermont                 611725
Idaho                   607119
Name: state, dtype: int64

In [26]:
# Creating a list of region values using if-statement with for-loops

region = []

for value in ords_prods_custs_merged_2['state']:
  if (value in ['Maine', 'New Hampshire', 'Vermont', 'Massachusetts', 'Rhode Island', 'Connecticut', 'New York', 'Pennsylvania', 'New Jersey']):
    region.append('Northeast')
  elif (value in ['Wisconsin', 'Michigan', 'Illinois', 'Ohio', 'North Dakota', 'South Dakota', 'Nebraska', 'Minnesota', 'Iowa', 'Missouri']):
    region.append('Midwest')
  elif (value in ['Delaware', 'Maryland', 'District of Columbia', 'Virginia', 'West Virginia', 'North Carolina', 'South Carolina', 'Georgia', 'Florida', 'Kentucky', 'Tennessee', 'Mississippi', 'Alabama', 'Oklahoma', 'Texas', 'Arkansas', 'Louisiana']):
    region.append('South')
  else:
    region.append('West')

In [27]:
region

['Midwest',
 'Midwest',
 'Midwest',
 'Midwest',
 'Midwest',
 'Midwest',
 'Midwest',
 'Midwest',
 'Midwest',
 'Midwest',
 'Midwest',
 'Midwest',
 'Midwest',
 'Midwest',
 'Midwest',
 'Midwest',
 'Midwest',
 'Midwest',
 'Midwest',
 'Midwest',
 'Midwest',
 'Midwest',
 'Midwest',
 'Midwest',
 'Midwest',
 'Midwest',
 'Midwest',
 'Midwest',
 'Midwest',
 'Midwest',
 'Midwest',
 'Midwest',
 'Midwest',
 'Midwest',
 'Midwest',
 'Midwest',
 'Midwest',
 'Midwest',
 'Midwest',
 'Midwest',
 'Midwest',
 'Midwest',
 'Midwest',
 'Midwest',
 'Midwest',
 'Midwest',
 'Midwest',
 'Midwest',
 'Midwest',
 'Midwest',
 'Midwest',
 'Midwest',
 'Midwest',
 'Midwest',
 'Midwest',
 'Midwest',
 'Midwest',
 'Midwest',
 'Midwest',
 'Midwest',
 'Midwest',
 'Midwest',
 'Midwest',
 'Midwest',
 'Midwest',
 'Midwest',
 'Midwest',
 'Midwest',
 'Midwest',
 'Midwest',
 'Midwest',
 'Midwest',
 'Midwest',
 'Midwest',
 'Midwest',
 'Midwest',
 'Midwest',
 'Midwest',
 'Midwest',
 'Midwest',
 'Midwest',
 'Midwest',
 'Midwest',
 'Midwest',
 'Midwest',
 'Midwest',
 'Midwest',
 'Midwest',
 'Midwest',
 'Midwest',
 'Midwest',
 'Midwest',
 'Midwest',
 'Midwest',
 'Midwest',
 'Midwest',
 'Midwest',
 'Midwest',
 'Midwest',
 'Midwest',
 'Midwest',
 'Midwest',
 'Midwest',
 'Midwest',
 'Midwest',
 'Midwest',
 'Midwest',
 'Midwest',
 'Midwest',
 'Midwest',
 'Midwest',
 'Midwest',
 'Midwest',
 'Midwest',
 'Midwest',
 'Midwest',
 'Midwest',
 'Midwest',
 'Midwest',
 'Midwest',
 'Midwest',
 'Midwest',
 'Midwest',
 'Midwest',
 'Midwest',
 'Midwest',
 'Midwest',
 'Midwest',
 'Midwest',
 'Midwest',
 'Midwest',
 'Midwest',
 'Midwest',
 'Midwest',
 'Midwest',
 'Midwest',
 'Midwest',
 'Midwest',
 'Midwest',
 'Midwest',
 'Midwest',
 'Midwest',
 'Midwest',
 'Midwest',
 'Midwest',
 'Midwest',
 'Midwest',
 'Midwest',
 'Northeast',
 'Northeast',
 'Northeast',
 'Northeast',
 'Northeast',
 'Northeast',
 'Northeast',
 'Northeast',
 'Northeast',
 'Northeast',
 'Northeast',
 'Northeast',
 'Northeast',
 'Northeast',
 'Northeast',
 'Northeast',
 'Northeast',
 'Northeast',
 'Northeast',
 'Northeast',
 'Northeast',
 'Northeast',
 'Northeast',
 'Northeast',
 'Northeast',
 'Northeast',
 'Northeast',
 'Northeast',
 'Northeast',
 'Northeast',
 'Northeast',
 'Northeast',
 'Northeast',
 'Northeast',
 'Northeast',
 'Northeast',
 'Northeast',
 'Northeast',
 'Northeast',
 'Northeast',
 'Northeast',
 'Northeast',
 'Northeast',
 'Northeast',
 'Northeast',
 'Northeast',
 'Northeast',
 'Northeast',
 'Northeast',
 'Northeast',
 'Northeast',
 'Northeast',
 'Northeast',
 'Northeast',
 'Northeast',
 'Northeast',
 'Northeast',
 'Northeast',
 'Northeast',
 'Northeast',
 'Northeast',
 'Northeast',
 'Northeast',
 'Northeast',
 'Northeast',
 'Northeast',
 'Northeast',
 'Northeast',
 'Northeast',
 'Northeast',
 'Northeast',
 'Northeast',
 'Northeast',
 'Northeast',
 'Northeast',
 'Northeast',
 'Northeast',
 'Northeast',
 'Northeast',
 'Northeast',
 'Northeast',
 'Northeast',
 'Northeast',
 'Northeast',
 'Northeast',
 'Northeast',
 'Northeast',
 'Northeast',
 'Northeast',
 'Northeast',
 'Northeast',
 'Northeast',
 'Northeast',
 'Northeast',
 'Northeast',
 'Northeast',
 'Northeast',
 'Northeast',
 'Northeast',
 'Northeast',
 'Northeast',
 'Northeast',
 'Northeast',
 'Northeast',
 'Northeast',
 'Northeast',
 'Northeast',
 'Northeast',
 'Northeast',
 'Northeast',
 'Northeast',
 'Northeast',
 'Northeast',
 'Northeast',
 'Northeast',
 'Northeast',
 'Northeast',
 'Northeast',
 'Northeast',
 'Northeast',
 'Northeast',
 'Northeast',
 'Northeast',
 'Northeast',
 'Northeast',
 'Northeast',
 'Northeast',
 'Northeast',
 'Northeast',
 'Northeast',
 'Northeast',
 'Northeast',
 'Northeast',
 'Northeast',
 'Northeast',
 'Northeast',
 'Northeast',
 'Northeast',
 'Northeast',
 'Northeast',
 'Northeast',
 'Northeast',
 'Northeast',
 'Northeast',
 'Northeast',
 'Northeast',
 'Northeast',
 'Northeast',
 'Northeast',
 'Northeast',
 'Northeast',
 'Northeast',
 'Northeast',
 'Northeast',
 'Northeast',
 'Northeast',
 'Northeast',
 'Northeast',
 'Northeast',
 'Northeast',
 'Northeast',
 'Northeast',
 'Northeast',
 'Northeast',
 'Northeast',
 'Northeast',
 'Northeast',
 'Northeast',
 'Northeast',
 'Northeast',
 'Northeast',
 'Northeast',
 'Northeast',
 'Northeast',
 'Northeast',
 'Northeast',
 'Northeast',
 'Northeast',
 'Northeast',
 'Northeast',
 'Northeast',
 'Northeast',
 'Northeast',
 'Northeast',
 'Northeast',
 'Northeast',
 'Northeast',
 'Northeast',
 'Northeast',
 'Northeast',
 'Northeast',
 'Northeast',
 'Midwest',
 'Midwest',
 'Midwest',
 'Midwest',
 'Midwest',
 'Midwest',
 'Midwest',
 'Midwest',
 'Midwest',
 'Midwest',
 'Midwest',
 'Midwest',
 'Midwest',
 'Midwest',
 'Midwest',
 'Midwest',
 'Midwest',
 'Midwest',
 'Midwest',
 'Midwest',
 'Midwest',
 'Midwest',
 'Midwest',
 'Midwest',
 'Midwest',
 'Midwest',
 'Midwest',
 'Midwest',
 'Midwest',
 'Midwest',
 'Midwest',
 'Midwest',
 'Midwest',
 'Midwest',
 'Midwest',
 'Midwest',
 'Midwest',
 'Midwest',
 'Midwest',
 'Midwest',
 'Midwest',
 'Midwest',
 'Midwest',
 'Midwest',
 'Midwest',
 'Midwest',
 'Midwest',
 'Midwest',
 'Midwest',
 'Midwest',
 'Midwest',
 'Midwest',
 'Midwest',
 'Midwest',
 'Midwest',
 'Midwest',
 'Midwest',
 'Midwest',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 ...]

In [28]:
# Creating new 'region' column within df, using 'region' values

ords_prods_custs_merged_2['region'] = region

In [29]:
# Checking 'region' value counts

ords_prods_custs_merged_2['region'].value_counts(dropna = False)

South        10791885
West          9557733
Midwest       6332505
Northeast     5722736
Name: region, dtype: int64

In [30]:
# Checking shape

ords_prods_custs_merged_2.shape

(32404859, 29)

In [31]:
# Checking headers

pd.set_option('display.max_columns', None)
ords_prods_custs_merged_2.head(1)

,Unnamed: 0,Unnamed: 0_x,product_id,product_name,aisle_id,department_id,prices,Unnamed: 0_y,order_id,user_id,eval_set,order_number,order_day_of_week,order_hour_of_day,days_since_prior_order,first_order,add_to_cart_order,reordered,_merge,gender,state,age,date_joined,number_of_dependants,fam_status,income,max_order,loyalty_flag,region
0,0,0,1,Chocolate Sandwich Cookies,61,19,5.8,1987,3139998,138,prior,28,6,11,3.0,False,5,0,both,Male,Minnesota,81,8/1/2019,1,married,49620,32,Regular Customer,Midwest

In [32]:
# b. Determine whether there’s a difference in spending habits between the different U.S. regions

In [35]:
# Creating new column in df for average price of products

ords_prods_custs_merged_2['avg_order_cost_by_cust'] = ords_prods_custs_merged.groupby(['user_id'])['prices'].transform('mean')

In [37]:
ords_prods_custs_merged_2.head()

,Unnamed: 0,Unnamed: 0_x,product_id,product_name,aisle_id,department_id,prices,Unnamed: 0_y,order_id,user_id,eval_set,order_number,order_day_of_week,order_hour_of_day,days_since_prior_order,first_order,add_to_cart_order,reordered,_merge,gender,state,age,date_joined,number_of_dependants,fam_status,income,max_order,loyalty_flag,region,avg_order_cost_by_cust
0,0,0,1,Chocolate Sandwich Cookies,61,19,5.8,1987,3139998,138,prior,28,6,11,3.0,False,5,0,both,Male,Minnesota,81,8/1/2019,1,married,49620,32,Regular Customer,Midwest,6.935811
1,1,0,1,Chocolate Sandwich Cookies,61,19,5.8,1989,1977647,138,prior,30,6,17,20.0,False,1,1,both,Male,Minnesota,81,8/1/2019,1,married,49620,32,Regular Customer,Midwest,6.935811
2,467222,907,907,Premium Sliced Bacon,106,12,20.0,1960,3160996,138,prior,1,5,13,NaN,True,4,0,both,Male,Minnesota,81,8/1/2019,1,married,49620,32,Regular Customer,Midwest,6.935811
3,467223,907,907,Premium Sliced Bacon,106,12,20.0,1969,2254091,138,prior,10,5,14,6.0,False,1,1,both,Male,Minnesota,81,8/1/2019,1,married,49620,32,Regular Customer,Midwest,6.935811
4,490702,1000,1000,Apricots,18,10,12.9,1968,505689,138,prior,9,6,12,7.0,False,5,0,both,Male,Minnesota,81,8/1/2019,1,married,49620,32,Regular Customer,Midwest,6.935811

In [38]:
# Creating spender flag: low spender - less than 10

ords_prods_custs_merged_2.loc[ords_prods_custs_merged_2['avg_order_cost_by_cust'] < 10, 'spender_flag'] = 'Low spender'

In [39]:
# Creating spender flag: High spender - higher than or equal to 10

ords_prods_custs_merged_2.loc[ords_prods_custs_merged_2['avg_order_cost_by_cust'] >= 10, 'spender_flag'] = 'High spender'

In [40]:
ords_prods_custs_merged_2.head()

,Unnamed: 0,Unnamed: 0_x,product_id,product_name,aisle_id,department_id,prices,Unnamed: 0_y,order_id,user_id,eval_set,order_number,order_day_of_week,order_hour_of_day,days_since_prior_order,first_order,add_to_cart_order,reordered,_merge,gender,state,age,date_joined,number_of_dependants,fam_status,income,max_order,loyalty_flag,region,avg_order_cost_by_cust,spender_flag
0,0,0,1,Chocolate Sandwich Cookies,61,19,5.8,1987,3139998,138,prior,28,6,11,3.0,False,5,0,both,Male,Minnesota,81,8/1/2019,1,married,49620,32,Regular Customer,Midwest,6.935811,Low spender
1,1,0,1,Chocolate Sandwich Cookies,61,19,5.8,1989,1977647,138,prior,30,6,17,20.0,False,1,1,both,Male,Minnesota,81,8/1/2019,1,married,49620,32,Regular Customer,Midwest,6.935811,Low spender
2,467222,907,907,Premium Sliced Bacon,106,12,20.0,1960,3160996,138,prior,1,5,13,NaN,True,4,0,both,Male,Minnesota,81,8/1/2019,1,married,49620,32,Regular Customer,Midwest,6.935811,Low spender
3,467223,907,907,Premium Sliced Bacon,106,12,20.0,1969,2254091,138,prior,10,5,14,6.0,False,1,1,both,Male,Minnesota,81,8/1/2019,1,married,49620,32,Regular Customer,Midwest,6.935811,Low spender
4,490702,1000,1000,Apricots,18,10,12.9,1968,505689,138,prior,9,6,12,7.0,False,5,0,both,Male,Minnesota,81,8/1/2019,1,married,49620,32,Regular Customer,Midwest,6.935811,Low spender

In [41]:
crosstab = pd.crosstab(ords_prods_custs_merged_2['region'], ords_prods_custs_merged_2['spender_flag'], dropna = False)

In [42]:
crosstab

spender_flag  High spender  Low spender
region
Midwest              23984      6308521
Northeast            18642      5704094
South                40579     10751306
West                 36523      9521210

In [43]:
# High spender percentages by region

Midwest = (23984/(123984+6308521))*100
Northeast = (18642/(18642+5704094))*100
South = (40579/(40579+10751306))*100
West = (36523/(36523+9521210))*100

In [44]:
# Percentage Results
Midwest, Northeast, South, West

(0.3728562978186569,
 0.3257532760553693,
 0.3760140142338433,
 0.3821303650143815)

In [45]:
# There is not a significant difference between the regions in terms of spending habits.
# The South region had the highest amount of customers that were high spenders but the Midwest region had a higher percentage of population that were high spenders.

In [ ]:
# The Instacart CFO isn’t interested in customers who don’t generate much revenue for the app.
# Create an exclusion flag for low-activity customers (customers with less than 5 orders) and exclude them from the data.
# Make sure you export this sample

# 05. Excluding Low-Activity Customers

In [46]:
# Creating low-activity flag - customers w/ less than 5 orders

ords_prods_custs_merged_2.loc[ords_prods_custs_merged_2['max_order'] < 5, 'activity_flag'] = 'Low activity'

In [47]:
# Creating low-activity flag - customers w/ more than 5 orders

ords_prods_custs_merged_2.loc[ords_prods_custs_merged_2['max_order'] >= 5, 'activity_flag'] = 'Normal activity'

In [48]:
# Checking values under 'activity_flag' column

ords_prods_custs_merged_2['activity_flag'].value_counts(dropna = False)

Normal activity    30964564
Low activity        1440295
Name: activity_flag, dtype: int64

In [50]:
# Creating df with only 'Low activity' customers

ords_prods_low_activity_custs = ords_prods_custs_merged_2[ords_prods_custs_merged_2['activity_flag']=='Low activity']

In [51]:
# Checking 'max_order' value count of low activity df

ords_prods_low_activity_custs['max_order'].value_counts(dropna = False)

4    753543
3    686741
2         6
1         5
Name: max_order, dtype: int64

In [52]:
# Creating df with 'Normal activity' customers

ords_prods_norm_activity_custs = ords_prods_custs_merged_2[ords_prods_custs_merged_2['activity_flag']=='Normal activity']

In [53]:
# Checking 'max_order' value count of normal activity df

ords_prods_norm_activity_custs['max_order'].value_counts(dropna = False)

99    1171333
8      811843
6      811396
9      810213
7      803979
       ...
93      50333
90      48328
97      44949
98      44587
96      40453
Name: max_order, Length: 95, dtype: int64

In [54]:
# Exporting dataframe containing normal activity customers

ords_prods_norm_activity_custs.to_csv('ords_prods_normal_activity_custs.csv')

In [55]:
# The marketing and business strategy units at Instacart want to create more-relevant marketing strategies for different products and are,
# thus, curious about customer profiling in their database. Create a profiling variable based on age, income, certain goods in the “department_id” column, and number of dependents. You might also use the “orders_day_of_the_week” and “order_hour_of_day” columns if you can think of a way they would impact customer profiles.
# (Hint: As an example, try thinking of what characteristics would lead you to the profile “Single adult” or “Young parent.

# 06. Customer Profiling

In [56]:
# Checking headers

ords_prods_custs_merged_2.head(1)

,Unnamed: 0,Unnamed: 0_x,product_id,product_name,aisle_id,department_id,prices,Unnamed: 0_y,order_id,user_id,eval_set,order_number,order_day_of_week,order_hour_of_day,days_since_prior_order,first_order,add_to_cart_order,reordered,_merge,gender,state,age,date_joined,number_of_dependants,fam_status,income,max_order,loyalty_flag,region,avg_order_cost_by_cust,spender_flag,activity_flag
0,0,0,1,Chocolate Sandwich Cookies,61,19,5.8,1987,3139998,138,prior,28,6,11,3.0,False,5,0,both,Male,Minnesota,81,8/1/2019,1,married,49620,32,Regular Customer,Midwest,6.935811,Low spender,Normal activity

In [57]:
# Classifying Age Groups

In [58]:
# Checking age range of customers

ords_prods_custs_merged_2['age'].value_counts().sort_index()

18    500474
19    519606
20    502848
21    512527
22    513853
       ...
77    502120
78    495311
79    529742
80    515246
81    509284
Name: age, Length: 64, dtype: int64

In [59]:
# Classifying age groups using the if-statement w/ for-loops

generation = []

for value in ords_prods_custs_merged_2['age']:
  if (value >=18) and (value <=25):
    generation.append('Gen Z 18-25')
  elif (value >=26) and (value <=41):
    generation.append('Millennials 26-41')
  elif (value >=42) and (value <=57):
    generation.append('Gen X 42-57')
  elif (value >=58) and (value<=76):
    generation.append('Baby Boomers 58-76')
  else:
    generation.append('Silent Generation >76')

In [60]:
# Adding 'generation' column with results from generation list

ords_prods_custs_merged_2['generation'] = generation

In [61]:
# Check value counts of 'generation' column

ords_prods_custs_merged_2['generation'].value_counts(dropna = False)

Baby Boomers 58-76       9520639
Gen X 42-57              8187246
Millennials 26-41        8100082
Gen Z 18-25              4045189
Silent Generation >76    2551703
Name: generation, dtype: int64

In [62]:
# Classifying Income

In [63]:
# Checking income range of customers

ords_prods_custs_merged_2['income'].value_counts().sort_index()

25903      20
25911      28
25937      39
25941      31
25955     392
         ...
584097    826
590790     54
591089    176
592409    318
593901    640
Name: income, Length: 108012, dtype: int64

In [64]:
# Classifying income groups using if-statement w/ for-loops

income_group = []

for value in ords_prods_custs_merged_2['income']:
  if (value < 32000):
    income_group.append('Lower class <32K')
  elif (value >= 32000) and (value <= 53000):
    income_group.append('Lower-middle class 32K-53K')
  elif (value > 53000) and (value <= 107000):
    income_group.append('Middle class 53K-107K')
  elif (value > 107000) and (value <=374000):
    income_group.append('Upper middle class 107K-374K')
  else:
    income_group.append('Upper class >374K')

In [66]:
# Adding 'income_group' column with results from income_group list

ords_prods_custs_merged_2['income_group'] = income_group

In [67]:
ords_prods_custs_merged_2['income_group'].value_counts(dropna = False)

Middle class 53K-107K           15403902
Upper middle class 107K-374K    12772553
Lower-middle class 32K-53K       3651538
Lower class <32K                  517878
Upper class >374K                  58988
Name: income_group, dtype: int64

In [68]:
# Parent Status Based on Dependants

In [69]:
# Checking number of dependants

ords_prods_custs_merged_2['number_of_dependants'].value_counts(dropna = False)

3    8135109
0    8097503
2    8091143
1    8081104
Name: number_of_dependants, dtype: int64

In [70]:
# Classifying customers as parent/non-parent based on 'number_of_depedants' using loc() function

ords_prods_custs_merged_2.loc[ords_prods_custs_merged_2['number_of_dependants'] == 0, 'parent_status'] = 'Non-parent'
ords_prods_custs_merged_2.loc[ords_prods_custs_merged_2['number_of_dependants'] >= 1, 'parent_status'] = 'Parent'

In [71]:
# Checking values for 'parent_status' column

ords_prods_custs_merged_2['parent_status'].value_counts(dropna = False)

Parent        24307356
Non-parent     8097503
Name: parent_status, dtype: int64

In [72]:
# Checking columns

ords_prods_custs_merged_2.head(1)

,Unnamed: 0,Unnamed: 0_x,product_id,product_name,aisle_id,department_id,prices,Unnamed: 0_y,order_id,user_id,eval_set,order_number,order_day_of_week,order_hour_of_day,days_since_prior_order,first_order,add_to_cart_order,reordered,_merge,gender,state,age,date_joined,number_of_dependants,fam_status,income,max_order,loyalty_flag,region,avg_order_cost_by_cust,spender_flag,activity_flag,generation,income_group,parent_status
0,0,0,1,Chocolate Sandwich Cookies,61,19,5.8,1987,3139998,138,prior,28,6,11,3.0,False,5,0,both,Male,Minnesota,81,8/1/2019,1,married,49620,32,Regular Customer,Midwest,6.935811,Low spender,Normal activity,Silent Generation >76,Lower-middle class 32K-53K,Parent

In [73]:
# Listing Out Name of Weekday

In [75]:
# Creating weekday column based on 'orders_day_of_the_week'

ords_prods_custs_merged_2.loc[ords_prods_custs_merged_2['order_day_of_week'] == 0, 'weekday'] = 'Saturday'
ords_prods_custs_merged_2.loc[ords_prods_custs_merged_2['order_day_of_week'] == 1, 'weekday'] = 'Sunday'
ords_prods_custs_merged_2.loc[ords_prods_custs_merged_2['order_day_of_week'] == 2, 'weekday'] = 'Monday'
ords_prods_custs_merged_2.loc[ords_prods_custs_merged_2['order_day_of_week'] == 3, 'weekday'] = 'Tuesday'
ords_prods_custs_merged_2.loc[ords_prods_custs_merged_2['order_day_of_week'] == 4, 'weekday'] = 'Wednesday'
ords_prods_custs_merged_2.loc[ords_prods_custs_merged_2['order_day_of_week'] == 5, 'weekday'] = 'Thursday'
ords_prods_custs_merged_2.loc[ords_prods_custs_merged_2['order_day_of_week'] == 6, 'weekday'] = 'Friday'

In [76]:
# Checking values for 'weekday'

ords_prods_custs_merged_2['weekday'].value_counts(dropna = False)

Saturday     6204182
Sunday       5660230
Friday       4496490
Monday       4213830
Thursday     4205791
Tuesday      3840534
Wednesday    3783802
Name: weekday, dtype: int64

In [77]:
# Listing Out Department Names

In [78]:
# Creating department_name column based on department_id

ords_prods_custs_merged_2.loc[ords_prods_custs_merged_2['department_id'] == 1, 'department_name'] = 'Frozen'
ords_prods_custs_merged_2.loc[ords_prods_custs_merged_2['department_id'] == 2, 'department_name'] = 'Other'
ords_prods_custs_merged_2.loc[ords_prods_custs_merged_2['department_id'] == 3, 'department_name'] = 'Bakery'
ords_prods_custs_merged_2.loc[ords_prods_custs_merged_2['department_id'] == 4, 'department_name'] = 'Produce'
ords_prods_custs_merged_2.loc[ords_prods_custs_merged_2['department_id'] == 5, 'department_name'] = 'Alcohol'
ords_prods_custs_merged_2.loc[ords_prods_custs_merged_2['department_id'] == 6, 'department_name'] = 'International'
ords_prods_custs_merged_2.loc[ords_prods_custs_merged_2['department_id'] == 7, 'department_name'] = 'Beverages'
ords_prods_custs_merged_2.loc[ords_prods_custs_merged_2['department_id'] == 8, 'department_name'] = 'Pets'
ords_prods_custs_merged_2.loc[ords_prods_custs_merged_2['department_id'] == 9, 'department_name'] = 'Dry goods'
ords_prods_custs_merged_2.loc[ords_prods_custs_merged_2['department_id'] == 10, 'department_name'] = 'Bulk'
ords_prods_custs_merged_2.loc[ords_prods_custs_merged_2['department_id'] == 11, 'department_name'] = 'Personal care'
ords_prods_custs_merged_2.loc[ords_prods_custs_merged_2['department_id'] == 12, 'department_name'] = 'Meat seafood'
ords_prods_custs_merged_2.loc[ords_prods_custs_merged_2['department_id'] == 13, 'department_name'] = 'Pantry'
ords_prods_custs_merged_2.loc[ords_prods_custs_merged_2['department_id'] == 14, 'department_name'] = 'Breakfast'
ords_prods_custs_merged_2.loc[ords_prods_custs_merged_2['department_id'] == 15, 'department_name'] = 'Canned goods'
ords_prods_custs_merged_2.loc[ords_prods_custs_merged_2['department_id'] == 16, 'department_name'] = 'Dairy Eggs'
ords_prods_custs_merged_2.loc[ords_prods_custs_merged_2['department_id'] == 17, 'department_name'] = 'Household'
ords_prods_custs_merged_2.loc[ords_prods_custs_merged_2['department_id'] == 18, 'department_name'] = 'Babies'
ords_prods_custs_merged_2.loc[ords_prods_custs_merged_2['department_id'] == 19, 'department_name'] = 'Snacks'
ords_prods_custs_merged_2.loc[ords_prods_custs_merged_2['department_id'] == 20, 'department_name'] = 'Deli'
ords_prods_custs_merged_2.loc[ords_prods_custs_merged_2['department_id'] == 21, 'department_name'] = 'Missing'

In [79]:
# Checking values for 'department_name'

ords_prods_custs_merged_2['department_name'].value_counts(dropna = False)

Produce          9479291
Dairy Eggs       5398747
Snacks           2887550
Beverages        2688123
Frozen           2234743
Pantry           1875369
Bakery           1172428
Canned goods     1068058
Deli             1051249
Dry goods         866627
Household         738666
Meat seafood      708927
Breakfast         703033
Personal care     447572
Babies            423802
International     269253
Alcohol           153696
Pets               97716
Missing            69145
Other              36291
Bulk               34573
Name: department_name, dtype: int64

In [80]:
# Checking headers

ords_prods_custs_merged_2.head(1)

,Unnamed: 0,Unnamed: 0_x,product_id,product_name,aisle_id,department_id,prices,Unnamed: 0_y,order_id,user_id,eval_set,order_number,order_day_of_week,order_hour_of_day,days_since_prior_order,first_order,add_to_cart_order,reordered,_merge,gender,state,age,date_joined,number_of_dependants,fam_status,income,max_order,loyalty_flag,region,avg_order_cost_by_cust,spender_flag,activity_flag,generation,income_group,parent_status,weekday,department_name
0,0,0,1,Chocolate Sandwich Cookies,61,19,5.8,1987,3139998,138,prior,28,6,11,3.0,False,5,0,both,Male,Minnesota,81,8/1/2019,1,married,49620,32,Regular Customer,Midwest,6.935811,Low spender,Normal activity,Silent Generation >76,Lower-middle class 32K-53K,Parent,Friday,Snacks

In [ ]:
ords_prods_custs_merged_2.to_pickle('ords_prods_custs_merged_2.csv')